apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-service
  labels:
    app: supplier-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplier-service
  template:
    metadata:
      labels:
        app: supplier-service
    spec:
      containers:
        - name: supplier-service
          image: sashi20014/supplier-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
          readinessProbe:
            httpGet:
              path: /supplier-service
              port: 5003
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /supplier-service
              port: 5003
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: supplier-service
spec:
  selector:
    app: supplier-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: ClusterIP
