name: Build, Test, Deploy

on:
  push:
    branches: [main]

env:
  DOCKER_HUB_REPO: sashi20014/supplier-service
  AWS_EC2_HOST: ${{ secrets.AWS_EC2_PUBLIC_IP }}
  AWS_EC2_SSH_KEY: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
  SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Java (required for SonarCloud)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run unit tests
      - name: Run unit tests
        run: npm test

      # SonarCloud analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.organization=sashi153
            -Dsonar.projectKey=supplier-service
            -Dsonar.javascript.node.version=18

      # Build Docker image
      - name: Build Docker image
        run: docker build -t $DOCKER_HUB_REPO:${{ github.sha }} .

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      # Push to Docker Hub
      - name: Push to Docker Hub
        run: docker push $DOCKER_HUB_REPO:${{ github.sha }}

  deploy-to-ec2:
    needs: build-test-scan
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          # Properly format the private key with newlines
          echo "${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}" | sed 's/\\n/\n/g' > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

          # Add EC2 to known_hosts
          ssh-keyscan ${{ secrets.AWS_EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

          # Verify SSH connection works
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} "echo 'SSH successful!'"
